sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t lenestopage/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lenestopage/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-reach"
  env: "Dockerreach-env"
  bucket_name: "elasticbeanstalk-us-east-2-581451982654"
  bucket_path: "docker-reach"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
